### PR TITLE
Update Purpose Consent Proposal comparison.md

### PR DESCRIPTION
**Pull request by shilpa-padgaonkar**
Added DT-view

@bigludo7 : Even though the text for point "What is expected for each /authorize call?" seems pretty long, I believe it is in alignment with your proposal. Please point out if it's not so and there are differences. 

For the purpose part, I have added a simple recommendation to get it checked with OpenID colleagues.

#### What type of PR is this?

Add one of the following kinds:
* correction
* enhancement/feature
* cleanup
* documentation
* subproject management
* tests

#### Which issue(s) this PR fixes:

Fixes #

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by shilpa-padgaonkar** [comment]
@bigludo7 Could you kindly merge this?

**Review by bigludo7 — COMMENTED** [review]
Merged DT contribution

**Comment by shilpa-padgaonkar** [comment]
@bigludo7 : strange that I see the PR still open

**Comment by shilpa-padgaonkar** [comment]
@bigludo7 thanks now it works :)

**Pull request merged**
